const ROUTE_CATALOG = [
  ["ROUTE_1", "1ばんどうろ"],
  ["ROUTE_2", "2ばんどうろ"],
  ["ROUTE_22", "22ばんどうろ"],
  ["VIRIDIAN_FOREST", "トキワのもり"],
  ["ROUTE_3", "3ばんどうろ"],
  ["MT_MOON_1F", "オツキミやま 1階"],
  ["MT_MOON_B1F", "オツキミやま 地下1階"],
  ["MT_MOON_B2F", "オツキミやま 地下2階"],
  ["ROUTE_4", "4ばんどうろ"],
  ["ROUTE_24", "24ばんどうろ"],
  ["ROUTE_25", "25ばんどうろ"],
  ["ROUTE_9", "9ばんどうろ"],
  ["ROUTE_5", "5ばんどうろ"],
  ["ROUTE_6", "6ばんどうろ"],
  ["ROUTE_11", "11ばんどうろ"],
  ["ROCK_TUNNEL_1F", "イワヤマトンネル 地下1階"],
  ["ROCK_TUNNEL_B1F", "イワヤマトンネル 地下2階"],
  ["ROUTE_10", "10ばんどうろ"],
  ["ROUTE_12", "12ばんどうろ"],
  ["ROUTE_8", "8ばんどうろ"],
  ["ROUTE_7", "7ばんどうろ"],
  ["POKEMON_TOWER_1F", "シオン／ポケモンタワー 1階"],
  ["POKEMON_TOWER_2F", "シオン／ポケモンタワー 2階"],
  ["POKEMON_TOWER_3F", "シオン／ポケモンタワー 3階"],
  ["POKEMON_TOWER_4F", "シオン／ポケモンタワー 4階"],
  ["POKEMON_TOWER_5F", "シオン／ポケモンタワー 5階"],
  ["POKEMON_TOWER_6F", "シオン／ポケモンタワー 6階"],
  ["POKEMON_TOWER_7F", "シオン／ポケモンタワー 7階"],
  ["ROUTE_13", "13ばんどうろ"],
  ["ROUTE_14", "14ばんどうろ"],
  ["ROUTE_15", "15ばんどうろ"],
  ["ROUTE_16", "16ばんどうろ"],
  ["ROUTE_17", "17ばんどうろ"],
  ["ROUTE_18", "18ばんどうろ"],
  ["SAFARI_ZONE_CENTER", "サファリゾーン 中央広場"],
  ["SAFARI_ZONE_EAST", "サファリゾーン 第1エリア"],
  ["SAFARI_ZONE_2", "サファリゾーン 第2エリア"],
  ["SAFARI_ZONE_3", "サファリゾーン 第3エリア"],
  ["ROUTE_19", "19ばんすいどう"],
  ["ROUTE_20", "20ばんすいどう"],
  ["SEAFOAM_ISLANDS_1F", "ふたごじま 1階"],
  ["SEAFOAM_ISLANDS_B1F", "ふたごじま 地下1階"],
  ["SEAFOAM_ISLANDS_B2F", "ふたごじま 地下2階"],
  ["SEAFOAM_ISLANDS_B3F", "ふたごじま 地下3階"],
  ["SEAFOAM_ISLANDS_B4F", "ふたごじま 地下4階"],
  ["POKEMON_MANSION_1F", "グレン／ポケモンやしき 1階"],
  ["POKEMON_MANSION_2F", "グレン／ポケモンやしき 2階"],
  ["POKEMON_MANSION_3F", "グレン／ポケモンやしき 3階"],
  ["POKEMON_MANSION_B1F", "グレン／ポケモンやしき 地下1階"],
  ["ROUTE_21", "21ばんすいどう"],
  ["CERULEAN_CAVE_1F", "ななしのどうくつ 1階"],
  ["CERULEAN_CAVE_2F", "ななしのどうくつ 2階"],
  ["CERULEAN_CAVE_B1F", "ななしのどうくつ 地下1階"],
  ["POWER_PLANT", "むじんはつでんしょ"],
  ["ROUTE_23", "23ばんどうろ"],
  ["VICTORY_ROAD_2F", "チャンピオンロード 2階"],
  ["VICTORY_ROAD_3F", "チャンピオンロード 3階"],
  ["VICTORY_ROAD_1F", "チャンピオンロード 1階"],
  ["DIGLETTS_CAVE", "ディグダのあな 地下1階"],
] as const;

export type RouteId = (typeof ROUTE_CATALOG)[number][0];

export const ROUTE_ORDER: readonly RouteId[] = ROUTE_CATALOG.map(([id]) => id);

export const JAPANESE_ROUTE_NAMES_BY_ID = Object.fromEntries(ROUTE_CATALOG) as Readonly<
  Record<(typeof ROUTE_ORDER)[number], string>
>;

export const ENGLISH_ROUTE_NAMES_BY_ID: Readonly<Record<RouteId, string>> = {
  ROUTE_1: "Route 1",
  ROUTE_2: "Route 2",
  ROUTE_22: "Route 22",
  VIRIDIAN_FOREST: "Viridian Forest",
  ROUTE_3: "Route 3",
  MT_MOON_1F: "Mt. Moon 1F",
  MT_MOON_B1F: "Mt. Moon B1F",
  MT_MOON_B2F: "Mt. Moon B2F",
  ROUTE_4: "Route 4",
  ROUTE_24: "Route 24",
  ROUTE_25: "Route 25",
  ROUTE_9: "Route 9",
  ROUTE_5: "Route 5",
  ROUTE_6: "Route 6",
  ROUTE_11: "Route 11",
  ROCK_TUNNEL_1F: "Rock Tunnel 1F",
  ROCK_TUNNEL_B1F: "Rock Tunnel B1F",
  ROUTE_10: "Route 10",
  ROUTE_12: "Route 12",
  ROUTE_8: "Route 8",
  ROUTE_7: "Route 7",
  POKEMON_TOWER_1F: "Lavender Town / Pokemon Tower 1F",
  POKEMON_TOWER_2F: "Lavender Town / Pokemon Tower 2F",
  POKEMON_TOWER_3F: "Lavender Town / Pokemon Tower 3F",
  POKEMON_TOWER_4F: "Lavender Town / Pokemon Tower 4F",
  POKEMON_TOWER_5F: "Lavender Town / Pokemon Tower 5F",
  POKEMON_TOWER_6F: "Lavender Town / Pokemon Tower 6F",
  POKEMON_TOWER_7F: "Lavender Town / Pokemon Tower 7F",
  ROUTE_13: "Route 13",
  ROUTE_14: "Route 14",
  ROUTE_15: "Route 15",
  ROUTE_16: "Route 16",
  ROUTE_17: "Route 17",
  ROUTE_18: "Route 18",
  SAFARI_ZONE_CENTER: "Safari Zone Center Area",
  SAFARI_ZONE_EAST: "Safari Zone Area 1",
  SAFARI_ZONE_2: "Safari Zone Area 2",
  SAFARI_ZONE_3: "Safari Zone Area 3",
  ROUTE_19: "Route 19",
  ROUTE_20: "Route 20",
  SEAFOAM_ISLANDS_1F: "Seafoam Islands 1F",
  SEAFOAM_ISLANDS_B1F: "Seafoam Islands B1F",
  SEAFOAM_ISLANDS_B2F: "Seafoam Islands B2F",
  SEAFOAM_ISLANDS_B3F: "Seafoam Islands B3F",
  SEAFOAM_ISLANDS_B4F: "Seafoam Islands B4F",
  POKEMON_MANSION_1F: "Cinnabar Island / Pokemon Mansion 1F",
  POKEMON_MANSION_2F: "Cinnabar Island / Pokemon Mansion 2F",
  POKEMON_MANSION_3F: "Cinnabar Island / Pokemon Mansion 3F",
  POKEMON_MANSION_B1F: "Cinnabar Island / Pokemon Mansion B1F",
  ROUTE_21: "Route 21",
  CERULEAN_CAVE_1F: "Cerulean Cave 1F",
  CERULEAN_CAVE_2F: "Cerulean Cave 2F",
  CERULEAN_CAVE_B1F: "Cerulean Cave B1F",
  POWER_PLANT: "Power Plant",
  ROUTE_23: "Route 23",
  VICTORY_ROAD_2F: "Victory Road 2F",
  VICTORY_ROAD_3F: "Victory Road 3F",
  VICTORY_ROAD_1F: "Victory Road 1F",
  DIGLETTS_CAVE: "Diglett's Cave B1F",
};
