const ROUTE_CATALOG = [
  ["ROUTE_1", "1ばんどうろ", "Route 1"],
  ["ROUTE_2", "2ばんどうろ", "Route 2"],
  ["ROUTE_22", "22ばんどうろ", "Route 22"],
  ["VIRIDIAN_FOREST", "トキワのもり", "Viridian Forest"],
  ["ROUTE_3", "3ばんどうろ", "Route 3"],
  ["MT_MOON_1F", "オツキミやま 1階", "Mt. Moon 1F"],
  ["MT_MOON_B1F", "オツキミやま 地下1階", "Mt. Moon B1F"],
  ["MT_MOON_B2F", "オツキミやま 地下2階", "Mt. Moon B2F"],
  ["ROUTE_4", "4ばんどうろ", "Route 4"],
  ["ROUTE_24", "24ばんどうろ", "Route 24"],
  ["ROUTE_25", "25ばんどうろ", "Route 25"],
  ["ROUTE_9", "9ばんどうろ", "Route 9"],
  ["ROUTE_5", "5ばんどうろ", "Route 5"],
  ["ROUTE_6", "6ばんどうろ", "Route 6"],
  ["ROUTE_11", "11ばんどうろ", "Route 11"],
  ["ROCK_TUNNEL_1F", "イワヤマトンネル 地下1階", "Rock Tunnel 1F"],
  ["ROCK_TUNNEL_B1F", "イワヤマトンネル 地下2階", "Rock Tunnel B1F"],
  ["ROUTE_10", "10ばんどうろ", "Route 10"],
  ["ROUTE_12", "12ばんどうろ", "Route 12"],
  ["ROUTE_8", "8ばんどうろ", "Route 8"],
  ["ROUTE_7", "7ばんどうろ", "Route 7"],
  ["POKEMON_TOWER_1F", "シオン／ポケモンタワー 1階", "Lavender Town / Pokemon Tower 1F"],
  ["POKEMON_TOWER_2F", "シオン／ポケモンタワー 2階", "Lavender Town / Pokemon Tower 2F"],
  ["POKEMON_TOWER_3F", "シオン／ポケモンタワー 3階", "Lavender Town / Pokemon Tower 3F"],
  ["POKEMON_TOWER_4F", "シオン／ポケモンタワー 4階", "Lavender Town / Pokemon Tower 4F"],
  ["POKEMON_TOWER_5F", "シオン／ポケモンタワー 5階", "Lavender Town / Pokemon Tower 5F"],
  ["POKEMON_TOWER_6F", "シオン／ポケモンタワー 6階", "Lavender Town / Pokemon Tower 6F"],
  ["POKEMON_TOWER_7F", "シオン／ポケモンタワー 7階", "Lavender Town / Pokemon Tower 7F"],
  ["ROUTE_13", "13ばんどうろ", "Route 13"],
  ["ROUTE_14", "14ばんどうろ", "Route 14"],
  ["ROUTE_15", "15ばんどうろ", "Route 15"],
  ["ROUTE_16", "16ばんどうろ", "Route 16"],
  ["ROUTE_17", "17ばんどうろ", "Route 17"],
  ["ROUTE_18", "18ばんどうろ", "Route 18"],
  ["SAFARI_ZONE_CENTER", "サファリゾーン 中央広場", "Safari Zone Center Area"],
  ["SAFARI_ZONE_EAST", "サファリゾーン 第1エリア", "Safari Zone Area 1"],
  ["SAFARI_ZONE_2", "サファリゾーン 第2エリア", "Safari Zone Area 2"],
  ["SAFARI_ZONE_3", "サファリゾーン 第3エリア", "Safari Zone Area 3"],
  ["ROUTE_19", "19ばんすいどう", "Route 19"],
  ["ROUTE_20", "20ばんすいどう", "Route 20"],
  ["SEAFOAM_ISLANDS_1F", "ふたごじま 1階", "Seafoam Islands 1F"],
  ["SEAFOAM_ISLANDS_B1F", "ふたごじま 地下1階", "Seafoam Islands B1F"],
  ["SEAFOAM_ISLANDS_B2F", "ふたごじま 地下2階", "Seafoam Islands B2F"],
  ["SEAFOAM_ISLANDS_B3F", "ふたごじま 地下3階", "Seafoam Islands B3F"],
  ["SEAFOAM_ISLANDS_B4F", "ふたごじま 地下4階", "Seafoam Islands B4F"],
  ["POKEMON_MANSION_1F", "グレン／ポケモンやしき 1階", "Cinnabar Island / Pokemon Mansion 1F"],
  ["POKEMON_MANSION_2F", "グレン／ポケモンやしき 2階", "Cinnabar Island / Pokemon Mansion 2F"],
  ["POKEMON_MANSION_3F", "グレン／ポケモンやしき 3階", "Cinnabar Island / Pokemon Mansion 3F"],
  [
    "POKEMON_MANSION_B1F",
    "グレン／ポケモンやしき 地下1階",
    "Cinnabar Island / Pokemon Mansion B1F",
  ],
  ["ROUTE_21", "21ばんすいどう", "Route 21"],
  ["CERULEAN_CAVE_1F", "ななしのどうくつ 1階", "Cerulean Cave 1F"],
  ["CERULEAN_CAVE_2F", "ななしのどうくつ 2階", "Cerulean Cave 2F"],
  ["CERULEAN_CAVE_B1F", "ななしのどうくつ 地下1階", "Cerulean Cave B1F"],
  ["POWER_PLANT", "むじんはつでんしょ", "Power Plant"],
  ["ROUTE_23", "23ばんどうろ", "Route 23"],
  ["VICTORY_ROAD_2F", "チャンピオンロード 2階", "Victory Road 2F"],
  ["VICTORY_ROAD_3F", "チャンピオンロード 3階", "Victory Road 3F"],
  ["VICTORY_ROAD_1F", "チャンピオンロード 1階", "Victory Road 1F"],
  ["DIGLETTS_CAVE", "ディグダのあな 地下1階", "Diglett's Cave B1F"],
] as const;

export type RouteId = (typeof ROUTE_CATALOG)[number][0];

export const ROUTE_ORDER: readonly RouteId[] = ROUTE_CATALOG.map(([id]) => id);

export const JAPANESE_ROUTE_NAMES_BY_ID = Object.fromEntries(
  ROUTE_CATALOG.map(([id, japaneseName]) => [id, japaneseName]),
) as Readonly<Record<RouteId, string>>;

export const ENGLISH_ROUTE_NAMES_BY_ID = Object.fromEntries(
  ROUTE_CATALOG.map(([id, , englishName]) => [id, englishName]),
) as Readonly<Record<RouteId, string>>;
